name: Packaging

on:
  - push

jobs:
  format:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4.0.0
        with:
          python-version: "3.13"

      - name: Install tox
        run: python -m pip install tox

      - name: Run black
        run: tox -e format

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4.0.0
        with:
          python-version: "3.13"

      - name: Install tox
        run: python -m pip install tox

      - name: Run flake8
        run: tox -e lint

  typecheck:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4.0.0
        with:
          python-version: "3.13"

      - name: Install tox
        run: python -m pip install tox

      - name: Run mypy
        run: tox -e typecheck

  test-color-a11y:
    name: Test color accessibility
    runs-on: ubuntu-latest

    strategy:
      matrix:
        text-color:
          - value: "#000000"
          - value: "#33A5F3"
          - value: "#59FFE9"
          - value: "#999999"
        background-color:
          - value: "#000000"
          - value: "#336633"
          - value: "#989A5F"
        standard:
          - name: "WCAG"
            level: "AA"
          - name: "WCAG"
            level: "AAA"

    steps:
      - name: Check accessibility
        run: |
          echo Checking ${{ matrix.text-color.value }} on ${{ matrix.background-color.value }} for ${{ matrix.standard.name }} level ${{ matrix.standard.level }}
